branch-defaults:
  default:
    environment: Peerprep54frontend-env
environment-defaults:
  Peerprep54frontend-env:
    branch: null
    repository: null
global:
  application_name: Peerprep54Frontend
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
