branch-defaults:
  master:
    environment: Peerprepuserservice-env
global:
  application_name: peerprep-user-service
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2 v3.4.19 running Docker
  default_region: us-east-2
  sc: git
