branch-defaults:
  default:
    environment: Peerprepcommunicationserviceenv-env
environment-defaults:
  Peerprepcommunicationserviceenv-env:
    branch: null
    repository: null
global:
  application_name: Peerprepcommunicationservice-env
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
