export const STATUS_CODE_CREATED = 201
export const STATUS_CODE_CONFLICT = 409
export const STATUS_CODE_OK = 200
export const STATUS_CODE_UNAUTHORIZED = 401
export const STATUS_CODE_BAD_REQUEST = 400
export const STATUS_INTERNAL_SERVER_ERROR = 500

