name: User Service CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      ENV: PROD
      PORT: 8002
      DB_CLOUD_URI: ${{ secrets.DB_CLOUD_URI }}
      EMAIL_CONFIRMATION_URI: ${{ secrets.EMAIL_CONFIRMATION_URI }}
      EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
      EMAIL_MAILER: ${{ secrets.EMAIL_MAILER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_CONFIRMATION_SECRET: ${{ secrets.EMAIL_CONFIRMATION_SECRET }}
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        working-directory: ./backend/user-service
        run: npm ci
      - name: Run Tests
        working-directory: ./backend/user-service
        run: npm test
